# Config file for automatic testing at travis-ci.org

language: python

# Use container based infrastructure
sudo: false

env:
  global:
    # encrypted Sauce Labs sub-account user name
    - secure: lNbb7g6bjHssNvj02PMAhdRMLTje0+WsYRxy7hdoPGJd5uCm3rx5Ha7yYmpv+6hj8SIA6QuE0viKVnife2Eyets99mMuYtsxE+NfHr19HpPEQPUdph3C5q93tupv+vJ52NQnPkb92PNAxDcM4+F+NQrlUBzVhoPjD/8y3whjFmE=
    # encrypted Sauce Labs sub-account token
    - secure: PiQisj0TKzfcoSuJe8nCiE3oKz1OT8IW+9lLA73lrHutY/yJrDlGrLoFBp20iIquVOKpGPX1DH1GvHVZeoiiV3qpaF/lJXmmacJte/FrdiVtQ9ezQYtRkY0UGiF+WnqfBPyGBHma9LszGcKHUIg+sXyQ/tIFFhq7U1vMKSPTHJ4=
    # encrypted Code Climate token
    - secure: gCi1UP9rgOnfvLT+UNiQkysnXUKvMi5ichNwPNxiXkLYlc66bJLIc/h8YI3V9vV4ICzyMJqEDHXV7T8NP0tsdxdNdEQNvStoaleLz7xsbjW7MZ2XxF13xncG6fksYr/5cjhBbiwg06HTn/VH+TD1FT1u9WUe+0/BJSx1JMnJQgs=
  matrix:
    - TOXENV=flake8
    - TOXENV=py34-dj18-cms31-fe
    - TOXENV=py34-dj17-cms31-fe
    - TOXENV=py34-dj17-cms30-fe
    - TOXENV=py34-dj16-cms31-fe
    - TOXENV=py34-dj16-cms30-fe
    - TOXENV=py33-dj17-cms31-fe
    - TOXENV=py33-dj17-cms30-fe
    - TOXENV=py33-dj16-cms31-fe
    - TOXENV=py33-dj16-cms30-fe
    - TOXENV=py27-dj18-cms31-fe
    - TOXENV=py27-dj17-cms31-fe
    - TOXENV=py27-dj17-cms30-fe
    - TOXENV=py27-dj16-cms31-fe
    - TOXENV=py27-dj16-cms30-fe
    - TOXENV=py26-dj16-cms31-fe
    - TOXENV=py26-dj16-cms30-fe

cache:
  directories:
    - $HOME/.wheelhouse

before_install:
  - npm install -g npm

install:
  - pip install tox
  - pip install coveralls

before_script:
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter
  - npm install

script:
  - tox -e $TOXENV

after_script:
  - codeclimate < tests/coverage/**/lcov.info

after_success: coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
